language: node_js
node_js:
  - stable

before_script:
  - npm install -g @angular/cli
script:
  - cd town
  - ng build --env prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master